# Generated by Django 4.1.1 on 2022-09-09 03:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0005_delete_image_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(default='No Image', max_length=255),
        ),
    ]
