# Generated by Django 4.1.1 on 2022-09-13 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0010_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
