# Generated by Django 4.1.1 on 2022-09-07 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_body', models.CharField(default='No status', max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2022, 9, 7, 23, 56, 31, 738289, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2022, 9, 7, 23, 56, 31, 739731, tzinfo=datetime.timezone.utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bunnybook.post')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
