# Generated by Django 4.1.1 on 2022-09-09 02:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='No Image', max_length=255, verbose_name='image'),
        ),
    ]
