# Generated by Django 4.1.1 on 2022-09-11 23:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0006_remove_post_photo_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(default='No File', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_body',
            field=models.CharField(default='No Status', max_length=100),
        ),
    ]
