# Generated by Django 4.1.1 on 2022-09-14 01:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunnybook', '0009_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=cloudinary.models.CloudinaryField(default='No File', max_length=255, null=True),
        ),
    ]
